---
- name: Tower Projects
  hosts: tower
  gather_facts: false
  connection: local
  collections:
    - ansible.tower
    
    
 # organization and state vars are injected via a survey in Ansible Tower.   


  tasks:      

# CREDENTIALS
  - name: ADD SSH credential into Ansible Tower
    ansible.tower.tower_credential:
      username: ec2-user
      password: "{{admin_password}}"
      name: "Windows Credential"
      kind: ssh
      organization: "{{ organization }}"
      tower_username: admin
      tower_password: "{{ admin_password }}"
      tower_host: "{{ ansible_host }}"
      tower_verify_ssl: false
      state: "{{ state }}"
      
  - name: ADD SSH credential into Ansible Tower
    ansible.tower.tower_credential:
      username: ec2-user
      password: "{{admin_password}}"
      name: "RHEL Credential"
      kind: ssh
      organization: "{{ organization }}"
      tower_username: admin
      tower_password: "{{ admin_password }}"
      tower_host: "{{ ansible_host }}"
      tower_verify_ssl: false
      state: "{{ state }}"
      
