---
- name: Tower Projects
  hosts: tower
  gather_facts: false
  connection: local
  collections:
    - awx.awx
    
    
 # organization and state vars are injected via a survey in Ansible Tower.   


  tasks:

          
      
 # INVENTORYS
  - name:  'INVENTORY - "{{ state }}"'
    awx.awx.tower_inventory:
      name: "Windows Inventory"
      organization: "{{ organization }}"
      tower_username: admin
      tower_password: "{{ admin_password }}"
      tower_host: "{{ ansible_host }}"
      tower_verify_ssl: false
      state: "{{ state }}"
    register: windows_inventory
    until: windows_inventory is success
    delay: 3
    retries: 5
    
    
    
  - name: 'INVENTORY - "{{ state }}"'
    awx.awx.tower_inventory:
      name: "RHEL Inventory"
      organization: "{{ organization }}"
      tower_username: admin
      tower_password: "{{ admin_password }}"
      tower_host: "{{ ansible_host }}"
      tower_verify_ssl: false
      state: "{{ state }}"
    register: rhel_inventory
    until: rhel_inventory is success
    delay: 3
    retries: 5
    
 
 
  - name: 'INVENTORY "{{ inv }}" - "{{ state }}"'
    awx.awx.tower_inventory:
      name: "OCP Tower Server REDHATSI"
      organization: "{{ organization }}"
      tower_username: admin
      tower_password: "{{ admin_password }}"
      tower_host: "{{ ansible_host }}"
      tower_verify_ssl: false
      state: "{{ state }}"
    var:
      inv: 'OCP Tower Server REDHATSI'
    register: ocp_tower_inventory
    until: ocp_tower_inventory is success
    delay: 3
    retries: 5
    
    
    
  - name: INVENTORY 
    awx.awx.tower_inventory:
      name: "ServiceNow Inventory Plugin"
      organization: "{{ organization }}"
      tower_username: admin
      tower_password: "{{ admin_password }}"
      tower_host: "{{ ansible_host }}"
      tower_verify_ssl: false
      state: "{{ state }}"
    register: snow_plugin_inventory
    until: snow_plugin_inventory is success
    delay: 3
    retries: 5
